server:
  port: 8888
spring:
  mvc:
    static-path-pattern: /resources/**  #这个会导致welcome page和favicon失效
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      static-locations: [classpath:/public/,classpath:/static/] #设置静态资源文件夹
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB



